name: Quickstart CI

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variables
        run: 'gci Env:'
        shell: pwsh
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate & detect quickstart solution changes
        id: validate_and_detect_qs_changes
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/validate-and-detect-quickstart-changes@master
        with:
          repo_name: ${{ github.repository }}
          trigger: ${{ github.event_name }}
          pr_number: ${{ github.event.number }}
          source_version: ${{ github.sha }}
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.build_is_required.outputs.quickstart_tool == 'porter'
        name: Install Porter
        id: install_porter
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter@master
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Parse Porter metadata
        id: parse_porter_metadata
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/parse-bundle-metadata@master
        with:
          metadata_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/porter.yaml
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Build Porter bundle
        id: build_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/build-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}
          invocation_image: ${{ steps.parse_porter_metadata.outputs.invocation_image }}
