name: Quickstart CI

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variables
        run: 'gci Env:'
        shell: pwsh
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Detect quickstart solution changes
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/detect-quickstart-solution-changes@master
        with:
          repo_name: ${{ github.repository }}
          trigger: ${{ github.event_name }}
          pr_number: ${{ github.event.number }}
          source_version: ${{ github.sha }}
      - name: Install Porter
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter@master
      - name: Parse Porter metadata
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/parse-bundle-metadata@master
        with:
          metadata_path: porter/sql-server-always-on/porter.yaml # get this value from previous step
