name: Quickstart CI

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variables
        run: 'gci Env:'
        shell: pwsh
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate & detect quickstart solution changes
        id: validate_and_detect_qs_changes
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/validate-and-detect-quickstart-changes@master
        with:
          repo_name: ${{ github.repository }}
          trigger: ${{ github.event_name }}
          pr_number: ${{ github.event.number }}
          source_version: ${{ github.sha }}
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Docker Registry Login
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_SERVER }}
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Install Porter
        id: install_porter
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/install-porter@master
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Build Porter bundle
        id: build_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/build-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true' && steps.validate_and_detect_qs_changes.outputs.quickstart_tool == 'porter'
        name: Publish Porter bundle
        id: publish_porter_bundle
        uses: endjin/CNAB.Quickstarts.GitHub.Actions/publish-porter-bundle@master
        with:
          bundle_dir: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Generate ARM template
        id: generate_arm_template
        uses: endjin/CNAB.ARM-Converter.GitHub.Actions/run-cnab-to-arm-tool@master
        with:
          bundle_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/.cnab/bundle.json
          output_path: ${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}/azuredeploy.json
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        run: |
          git status
          git diff
      - if: steps.validate_and_detect_qs_changes.outputs.build_is_required == 'true'
        name: Commit & push ARM template if updated
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: "Update ARM template for bundle '${{ steps.validate_and_detect_qs_changes.outputs.quickstart_solution_path }}'"
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

